name: Check Branch Sync

on:
  schedule:
    - cron: '0 0 * * *' # This runs the workflow daily at midnight UTC
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  check-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for differences
      run: |
        git fetch origin
        if ! git diff --quiet origin/main..origin/dev; then
          echo "Branches are not in sync"
          exit 1
        fi

    - name: Send notification
      if: failure()
      run: |
        echo "Branches 'main' and 'dev' are not in sync"
        # Here you can add commands to send a notification, for example, using curl to send a message to a Slack webhook
